services:
  express:
    image: ghcr.io/alexispet/final-test-alexandredaussin/tpdevops:main
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: userops
      DB_PASSWORD: userops
      DB_DATABASE: tpdevops
    # ports:
    #   - "80:3000"
    depends_on:
        db:
          condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.express-prod.rule=Host(`ec2-3-95-31-144.compute-1.amazonaws.com`)"
      - "traefik.http.routers.express-prod.entrypoints=prod"

  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: tpdevops
      MYSQL_USER: userops
      MYSQL_PASSWORD: userops
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=userops --password=userops --execute \"SHOW DATABASES;\""
      interval: 1m
      timeout: 20s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080
    
  traefik:
    image: traefik:v2.10
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.prod.address=:80"

    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"