services:
  express:
    image: ghcr.io/alexispet/final-test-alexandredaussin/tpdevops:develop
    environment:
      NODE_ENV: DEV
      DB_HOST: db
      DB_USER: userops
      DB_PASSWORD: userops
      DB_DATABASE: tpdevops
    # ports:
    #   - "3000:3000"
    depends_on:
        db:
          condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.express-dev.rule=Host(`ec2-3-86-213-89.compute-1.amazonaws.com`)"
      - "traefik.http.routers.express-dev.entrypoints=dev"

  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: tpdevops
      MYSQL_USER: userops
      MYSQL_PASSWORD: userops
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    ports:
      - 3307:3306
    healthcheck:
      test: "/usr/bin/mysql --user=userops --password=userops --execute \"SHOW DATABASES;\""
      interval: 1m
      timeout: 20s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8081:8080

  traefik:
    image: traefik:v2.10
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.dev.address=:3000"

    ports:
      - "3000:3000"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"