services:
  express:
    image: ghcr.io/alexispet/final-test-alexandredaussin/tpdevops:develop
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
        db:
          condition: service_healthy

  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    ports:
      - 3307:3306
    healthcheck:
      test: "/usr/bin/mysql --user=userops --password=userops --execute \"SHOW DATABASES;\""
      interval: 1m
      timeout: 20s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8081:8080